### PR TITLE
✅ Flask/Custom netflix sign in

### PR DESCRIPTION
**Pull request by starlightknown**
closes #ISSUE-NO

#### What does this PR do?

A custom sign in of netflix using Sawo SDK and Flask

#### Description of the task to be completed?

Usecase:
- A server side rendered clone for Signin page of the Netflix
- Using the "Add Custom Features" section of the form to build extra fields in a clone ui for netflix signin

#### How can this be manually tested?
cd to the project folder and run `python 3 app.py`

#### Screenshots (if appropriate)
![image]
netflix

home

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
@starlightknown I went to the deployed application. Upon going on signup button it shows 
img

Also when I click on the get started button it doesn't verify my email with OTP etc (How it's supposed to work) could you maybe look into that?

**Comment by starlightknown** [comment]
I thought it should be a Netflix clone so I added password field from the dashboard, lemme correct that then

**Comment by kaiwalyakoparkar** [comment]
> so

Yep it is a clone but sawo is passwordless authentication service so password field is unnecessary in the clone :)

**Comment by kaiwalyakoparkar** [comment]
@starlightknown is it ready for review or are you still working on it?

**Comment by starlightknown** [comment]
yep code is done

**Review by Sonichigo — APPROVED** [review]

**Comment by kaiwalyakoparkar** [comment]
Hey @starlightknown I can still see the password field. Can you share the correct deployed link?

**Comment by starlightknown** [comment]
I'm not sure how are you able to see the password section, I removed it from sawo dashboard and it's not done in code

**Comment by kaiwalyakoparkar** [comment]
> I'm not sure how are you able to see the password section, I removed it from sawo dashboard and it's not done in code

Have you deployed the this project somewhere?

**Pull request closed without merging**
