### PR TITLE
Responsive Sneaker Site with SAWO Authentication

### PR DESCRIPTION
**Pull request by Adit0507**
closes #ISSUE-NO

#### What does this PR do?
In this PR I have added a Responsive Ecommerce Sneaker Site with SAWO Authentication. 
I tried integrating a React project with SAWO but was running into some errors. As soon as I get over those I will add more good and sophisticated projects.

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Hey @Adit0507 Please shift this pr to this [Repo](https://github.com/Sawo-Community/Champs-Contributions)

**Comment by kaiwalyakoparkar** [comment]
Hey @Adit0507 do you need any help with this?

**Comment by Adit0507** [comment]
> Hey @Adit0507 do you need any help with this?

My college is currently in offline mode 🙃, I would have finished it earlier but as of now I'm bombarded with assignments. 

I'll do it as soon as I get some time 😊

**Comment by kaiwalyakoparkar** [comment]
Sure, I will close this pr then :smiley:

**Pull request closed without merging**
